Resources:
  AssetTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:provider.environment.ASSET_TABLE_NAME}
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: name
          AttributeType: S
        - AttributeName: org
          AttributeType: S
        - AttributeName: fileSize
          AttributeType: N
        - AttributeName: createdAt
          AttributeType: N
        - AttributeName: updatedAt
          AttributeType: N
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:provider.environment.ASSET_TABLE_READ_CAPACITY}
        WriteCapacityUnits: ${self:provider.environment.ASSET_TABLE_WRITE_CAPACITY}
      GlobalSecondaryIndexes:
        - IndexName: nameIndex
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: name
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:provider.environment.ASSET_TABLE_GSI_READ_CAPACITY}
            WriteCapacityUnits: ${self:provider.environment.ASSET_TABLE_GSI_WRITE_CAPACITY}
        - IndexName: fileSizeIndex
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: fileSize
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:provider.environment.ASSET_TABLE_GSI_READ_CAPACITY}
            WriteCapacityUnits: ${self:provider.environment.ASSET_TABLE_GSI_WRITE_CAPACITY}
        - IndexName: createdAtIndex
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:provider.environment.ASSET_TABLE_GSI_READ_CAPACITY}
            WriteCapacityUnits: ${self:provider.environment.ASSET_TABLE_GSI_WRITE_CAPACITY}
        - IndexName: updatedAtIndex
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: updatedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:provider.environment.ASSET_TABLE_GSI_READ_CAPACITY}
            WriteCapacityUnits: ${self:provider.environment.ASSET_TABLE_GSI_WRITE_CAPACITY}
        - IndexName: orgIndex
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: org
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:provider.environment.ASSET_TABLE_GSI_READ_CAPACITY}
            WriteCapacityUnits: ${self:provider.environment.ASSET_TABLE_GSI_WRITE_CAPACITY}
